version: "3.7"
name: "classbot"
services:

  # 1.) Classbot; this project
  classbot:
    image: ghcr.io/azure-agst/classbot-3.0
    tty: true
    environment:
      - DRIVER=Docker
      - DRIVER_HEADLESS=True
      - DRIVER_REMOTE=http://selenium:4444
    env_file:
      - .env

    # 1.2) Dependency
    # NOTE: Selenium takes about 30s to spin up
    #       Must be ready, otherwise Classbot panics
    depends_on:
      selenium:
        condition: service_healthy

  # 2.) Selenium Firefox
  selenium:
    image: selenium/standalone-firefox:4.3.0-20220706
    shm_size: 2g

    # 2.1) Health Check
    healthcheck:
      test: curl -f http://localhost:4444/status
      start_period: 30s
      retries: 3
